### ISSUE TITLE
Is mergesort() FreeBSD only?

### ISSUE THREAD

**Issue by edogawa23** [hselasky/midipp#1]
In commit  60c403d from August qsort() got changed to mergesort().
This is not included by stdlib.h in Linux, therefore my attempts to build for openSUSE fail after updating midipp to 2.0.0.
See the build logs for my package at
[https://build.opensuse.org/package/show/home:edogawa/midipp](url)

**Comment by hselasky** [comment]
Hi,

The code contains #ifdefs for qsort/mergesort. I'm surprised there is only qsort() under Linux.

```
Should I add #if defined(__linux__) || defined(__ANDROID__) ??

#ifdef __ANDROID__
        qsort(ptemp, n, sizeof(ptemp[0]), &MppSheetRowCompare);
#else
        mergesort(ptemp, n, sizeof(ptemp[0]), &MppSheetRowCompare);
#endif

```

--HPS

**Comment by edogawa23** [comment]
yes I read the code, but as I'm not very familiar with glibc i have no real clue how to deal with this. I searched a bit and found contradicting infos about qsort being in fact a mergesort algorithm, but from reading the source code I think it is not. Someone else said there is a msort() function, but my glibc doesn't provide such a call it seems.
I can try the #if defined ... change and patch my package for now, and report whether it works.

**Comment by edogawa23** [comment]
It builds now with [this patch ](https://build.opensuse.org/package/view_file/home:edogawa/midipp/midipp-qsort.patch?expand=1).

**Comment by hselasky** [comment]
https://github.com/hselasky/midipp/commit/08e4f8068146faad0e2db9a645d56d181507e136

FYI: The patch will be part of next release.
